language: ruby
rvm:
- 2.5.3
services:
- postgresql
before_script:
- psql -c 'create database cup_of_sugar_test;' -U postgres
- bundle exec rails db:create

script:
- bundle exec rails db:migrate RAILS_ENV=test
